[package]
name = "quiche-node-bindings"
version = "0.1.0"
edition = "2018"

[dependencies]
napi = "2"
napi-derive = "2"
quiche = "0.22.0"  # Use the latest stable version from crates.io
log = "0.4"

[lib]
crate-type = ["cdylib"]
